services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redis-ui:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  bucket:
    image: oittaa/gcp-storage-emulator
    command: start --default-bucket=storyteller
    environment:
      PORT: 9023
    ports:
      - "9023:9023"
    volumes:
      - ./storage:/storage
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PUBLIC_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
