[project]
name = "backend"
version = "0.1.0"
description = "Backend for StoryTeller application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.3",
    "motor>=3.6.0",
    "pydantic-settings>=2.6.0",
    "pydantic>=2.9.2",
    "uvicorn>=0.32.0",
]
